import type { Team, Player, ManagementMember, GalleryItem } from './types';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 't1',
    name: 'Bilasipara Strikers',
    short_name: 'BST',
    owner_name: 'Rafiqul Islam',
    captain_name: 'Jahidul Hasan',
    city: 'Bilasipara',
    primary_color: '#16a34a',
    secondary_color: '#d4af37',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 14,
  },
  {
    id: 't2',
    name: 'Khoraghat Super Kings',
    short_name: 'KSK',
    owner_name: 'Faruk Ahmed',
    captain_name: 'Anowar Hussain',
    city: 'Khoraghat',
    primary_color: '#22c55e',
    secondary_color: '#0f172a',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 15,
  },
  {
    id: 't3',
    name: 'Dhubri Tigers',
    short_name: 'DHT',
    owner_name: 'Mokbul Ali',
    captain_name: 'Suhail Tanvir',
    city: 'Dhubri',
    primary_color: '#059669',
    secondary_color: '#fbbf24',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 13,
  },
  {
    id: 't4',
    name: 'Royal Khoraghat Challengers',
    short_name: 'RKC',
    owner_name: 'Kamrul Hassan',
    captain_name: 'Aslam Parvez',
    city: 'Khoraghat',
    primary_color: '#10b981',
    secondary_color: '#ffffff',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 14,
  },
  {
    id: 't5',
    name: 'Assam Warriors',
    short_name: 'ASW',
    owner_name: 'Zakir Sheikh',
    captain_name: 'Rahimuddin Ahmed',
    city: 'Guwahati',
    primary_color: '#15803d',
    secondary_color: '#f59e0b',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 15,
  },
  {
    id: 't6',
    name: 'Brahmaputra XI',
    short_name: 'BPX',
    owner_name: 'Sultan Mahmud',
    captain_name: 'Shahidul Karim',
    city: 'Goalpara',
    primary_color: '#047857',
    secondary_color: '#38bdf8',
    logo_url: '/images/kpl-logo.jpg',
    squad_count: 14,
  },
];

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'p1',
    registration_number: 'KPL2026-001',
    full_name: 'Jahidul Hasan',
    role: 'All-Rounder',
    category: 'Icon',
    base_price: '₹ 2,000',
    team_name: 'Bilasipara Strikers',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Sold',
    contact: '+91 98765 43210',
    village: 'Bilasipara Ward 4',
  },
  {
    id: 'p2',
    registration_number: 'KPL2026-002',
    full_name: 'Anowar Hussain',
    role: 'Batter',
    category: 'Local',
    base_price: '₹ 1,500',
    team_name: 'Khoraghat Super Kings',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Sold',
    contact: '+91 98765 43211',
    village: 'Khoraghat Part 1',
  },
  {
    id: 'p3',
    registration_number: 'KPL2026-003',
    full_name: 'Suhail Tanvir',
    role: 'Bowler',
    category: 'Outstation',
    base_price: '₹ 1,500',
    team_name: 'Dhubri Tigers',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Sold',
    contact: '+91 98765 43212',
    village: 'Dhubri Town',
  },
  {
    id: 'p4',
    registration_number: 'KPL2026-004',
    full_name: 'Aslam Parvez',
    role: 'Wicketkeeper',
    category: 'Local',
    base_price: '₹ 1,000',
    team_name: 'Royal Khoraghat Challengers',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Sold',
    contact: '+91 98765 43213',
    village: 'Khoraghat Part 2',
  },
  {
    id: 'p5',
    registration_number: 'KPL2026-005',
    full_name: 'Rashidul Islam',
    role: 'Bowler',
    category: 'Local',
    base_price: '₹ 1,000',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Approved',
    contact: '+91 98765 43214',
    village: 'Bilasipara',
  },
  {
    id: 'p6',
    registration_number: 'KPL2026-006',
    full_name: 'Imran Ahmed',
    role: 'Batter',
    category: 'Outstation',
    base_price: '₹ 1,500',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Approved',
    contact: '+91 98765 43215',
    village: 'Goalpara',
  },
  {
    id: 'p7',
    registration_number: 'KPL2026-007',
    full_name: 'Nazmul Haque',
    role: 'All-Rounder',
    category: 'Local',
    base_price: '₹ 1,200',
    photo_url: '/images/kpl-logo.jpg',
    status: 'Pending',
    contact: '+91 98765 43216',
    village: 'Khoraghat',
  },
];

export const INITIAL_MANAGEMENT: ManagementMember[] = [
  {
    id: 'm1',
    name: 'Khurshid Alom',
    designation: 'President & Chairman',
    contact: '+91 98765 00001',
    photo_url: '/images/kpl-logo.jpg',
  },
  {
    id: 'm2',
    name: 'Nurul Islam',
    designation: 'General Secretary',
    contact: '+91 98765 00002',
    photo_url: '/images/kpl-logo.jpg',
  },
  {
    id: 'm3',
    name: 'Shah Jamal',
    designation: 'Tournament Director',
    contact: '+91 98765 00003',
    photo_url: '/images/kpl-logo.jpg',
  },
  {
    id: 'm4',
    name: 'Abdur Rahim',
    designation: 'Treasurer & Finance Head',
    contact: '+91 98765 00004',
    photo_url: '/images/kpl-logo.jpg',
  },
  {
    id: 'm5',
    name: 'Mokbul Ali',
    designation: 'Chief Umpiring Coordinator',
    contact: '+91 98765 00005',
    photo_url: '/images/kpl-logo.jpg',
  },
  {
    id: 'm6',
    name: 'Zakir Ahmed',
    designation: 'Media & Public Relations',
    contact: '+91 98765 00006',
    photo_url: '/images/kpl-logo.jpg',
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  { id: 1, photo_url: '/images/hero-1.jpg', caption: 'Season 2 Grand Finale Crowd', category: 'Match' },
  { id: 2, photo_url: '/images/hero-2.jpg', caption: 'Championship Trophy Unveiling', category: 'Trophy' },
  { id: 3, photo_url: '/images/hero-3.jpg', caption: 'Franchise Auction Gala Night', category: 'Auction' },
  { id: 4, photo_url: '/images/hero-4.jpg', caption: 'High Voltage Match Action', category: 'Match' },
  { id: 5, photo_url: '/images/hero-5.jpg', caption: 'Opening Ceremony Fireworks', category: 'Event' },
  { id: 6, photo_url: '/images/hero-6.jpg', caption: 'Closing Ceremony & Celebrations', category: 'Event' },
];
